# -*- coding: utf-8 -*-
"""mask_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JK1eE1hNrgyoSRb2X80bycRRKkoQLNsS
"""

import numpy as np

def crop_mask_contained(mask, crop_size=64):
    coords = np.argwhere(mask > 0)
    if coords.size == 0:
        return np.zeros((crop_size, crop_size), dtype=mask.dtype)

    y_min, x_min = coords.min(axis=0)
    y_max, x_max = coords.max(axis=0)

    y_center = (y_min + y_max) // 2
    x_center = (x_min + x_max) // 2

    half = crop_size // 2
    y1 = max(y_center - half, 0)
    x1 = max(x_center - half, 0)
    y2 = y1 + crop_size
    x2 = x1 + crop_size

    if y2 > mask.shape[0]:
        y2 = mask.shape[0]
        y1 = y2 - crop_size
    if x2 > mask.shape[1]:
        x2 = mask.shape[1]
        x1 = x2 - crop_size

    return mask[y1:y2, x1:x2]