# -*- coding: utf-8 -*-
"""semantic_features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JK1eE1hNrgyoSRb2X80bycRRKkoQLNsS
"""

import numpy as np
from skimage import measure
from scipy.spatial.distance import pdist

def extract_semantic_features(mask):
    """
    Extracts semantic features from a binary tumor mask.

    Parameters:
    - mask (np.ndarray): A 2D binary array with the segmented tumor.

    Returns:
    - dict: Dictionary with spiculation_proxy, compactness, solidity, diameter.
    """
    if np.sum(mask) == 0:
        return {
            'spiculation_proxy': 0,
            'compactness': 0,
            'solidity': 0,
            'diameter': 0
        }

    labeled_mask = measure.label(mask)
    regions = measure.regionprops(labeled_mask)
    if not regions:
        return {
            'spiculation_proxy': 0,
            'compactness': 0,
            'solidity': 0,
            'diameter': 0
        }

    region = max(regions, key=lambda r: r.area)
    coords = region.coords

    area = region.area
    perimeter = region.perimeter if region.perimeter != 0 else 1

    compactness = 4 * np.pi * area / (perimeter ** 2)
    solidity = region.solidity
    diameter = np.max(pdist(coords)) if len(coords) > 1 else 0
    spiculation_proxy = (perimeter ** 2) / area

    return {
        'spiculation_proxy': spiculation_proxy,
        'compactness': compactness,
        'solidity': solidity,
        'diameter': diameter
    }